package com.vikri.gcpagent

data class Capability(
    val id: String,
    val name: String,
    val emoji: String,
    val insight: String,
    val group: String
)

object CapabilityCatalog {
    val groups = listOf(
        "Riset & AI", "Build App", "DevTools & Agent", "DevOps & Delivery",
        "Data", "Konten & Media", "Sistem & Performa", "Keamanan",
        "Keuangan & Cloud", "Otomasi", "Operasional", "Jaringan",
        "Kualitas", "Growth & Konten", "Web & Live", "Notifikasi",
        "Ops & Recovery", "Kreatif & Game"
    )

    val all = listOf(
        Capability("combo-multi-agent-research", "Multi-Agent Deep Research", "🔬", "Riset mendalam multi-sumber yang diorkestrasi banyak agen: cari → baca → sintesis → laporan dengan sumber, dalam bahasa yang jelas.", "Riset & AI"),
        Capability("combo-token-efficiency", "Efficiency & Optimization Mastery", "⚡", "Fusion total efisiensi (restrukturisasi semua logika kode): menyatukan 300+ skill optimasi token, biaya, kinerja, dan resource — kompresi konteks (caveman/ponytail), FinOps cloud, benchmark & profiling loop, paralel/async patterns, optimasi SQL/database/index/vector, build & bundle optimization, LLM cost-aware pipeline, SLO/monitoring, cache & autoscaling, hingga autonomous optimization — satu kemampuan utuh untuk efisiensi maksimal di setiap lapisan stack.", "Sistem & Performa"),
        Capability("combo-mcp-tool-builder", "MCP Servers & Agent Tooling", "🔌", "Bangun dan integrasikan alat agen: pola server MCP yang aman, workflow berulang yang terotomasi, dan API yang dirancang untuk dipakai agen, bukan hanya manusia.", "DevTools & Agent"),
        Capability("combo-ai-native-app", "AI-Native App Builder", "🧠", "Aplikasi yang lahir dengan AI sebagai inti: UI yang manusiawi, backend/API yang siap generatif, media AI (gambar/video), dan pengalaman pengguna yang mulus.", "Build App"),
        Capability("combo-e2e-quality", "E2E Quality & Benchmark", "🧪", "Kualitas terukur: benchmark & evaluasi metodis, E2E otomatis, standar koding tegas, dan agen meng-inspeksi perilaku sendiri sebelum menyerahkan hasil.", "Kualitas"),
        Capability("combo-growth-content", "Growth, Brand & Content Engine", "📈", "Mesin pertumbuhan: temukan identitas brand, produksi konten berkarakter di banyak platform, dan bangun materi yang menarik investor & pasar secara konsisten.", "Growth & Konten"),
        Capability("combo-runtime-performance", "Modern Runtime & Performance", "🚀", "Kinerja maksimal di runtime modern: pilih runtime tepat, optimasi bundle/build, dan pola backend/frontend yang lahir cepat — latensi rendah, skala tinggi.", "Sistem & Performa"),
        Capability("combo-agent-systems", "Agent Systems & Orchestration", "🤖", "Sistem multi-agen produksi: pecah tugas, delegasikan ke subagen yang tepat, koordinasikan hasil paralel, dan jaga konteks tetap ramping sepanjang eksekusi.", "DevTools & Agent"),
        Capability("combo-research-ai-pipeline", "Research-to-AI Pipeline", "🧭", "Dari riset ke model produksi: alur MLE yang terstruktur, benchmark ketat, eksperimen terdokumentasi, dan hasil disajikan sebagai laporan/presentasi yang meyakinkan.", "Riset & AI"),
        Capability("combo-rag-knowledge", "RAG & Knowledge Graph", "📚", "Pengetahuan yang selalu terjangkau: indeks kodebase & dokumen jadi grafik semantik, retrieval RAG yang presisi, dan jawaban selalu berdasar sumber nyata.", "Riset & AI"),
        Capability("combo-devtools-dx", "DevTools & Developer Experience", "🛠️", "Pengalaman pengembang kelas dunia: dokumentasi hidup, CLI & alat yang nyaman, standar koding konsisten, dan umpan balik cepat dari pengujian otomatis.", "DevTools & Agent"),
        Capability("combo-media-generation", "AI Media & Presentation", "🎬", "Produksi media berbantuan AI: gambar/video generatif, slide yang dirancang baik, dan konten visual yang konsisten dengan brand — cepat dan profesional.", "Konten & Media"),
        Capability("combo-agentic-devops", "Agentic DevOps", "🤖", "DevOps yang dijalankan agen: pipeline CI/CD, review otomatis, debugging sistematis, dan remediasi mandiri — manusia mengawasi, agen mengeksekusi.", "DevOps & Delivery"),
        Capability("combo-mobile-cloud", "Mobile × Cloud Backend", "📱", "Aplikasi mobile ringan dengan mesin cloud: UI WebView/native yang minim, backend serveless, API aman, dan semua proses berat terjadi di cloud — APK tetap kecil.", "Build App"),
        Capability("combo-web3-secure", "Web3 Secure Engineering", "⛓️", "Kontrak pintar & dApps yang aman sejak desain: pahami attack vectors, uji menyeluruh, dan terapkan threat modeling sebelum jaringan utama.", "Keamanan"),
        Capability("combo-sql-data-workflow", "SQL & Data Workflow (Multi-Step)", "🗃️", "Workflow data menyeluruh yang benar-benar berjalan: buat skema SQL → isi data (dari file/Csv) → query agregasi → verifikasi hasil → laporan. Semua langkah dieksekusi nyata, bukan sekadar dijelaskan.", "Data"),
        Capability("combo-live-web-exec", "Live Web Execution", "🌐", "Eksekusi langsung terhadap web: ambil halaman/API publik, ekstrak data, olah bersama file lokal, lalu sajikan hasil — semua terpasang pada loop agen nyata.", "Web & Live"),
        Capability("combo-local-db-app", "Local DB & API App", "🗄️", "Bangun aplikasi data lokal-lengkap: database SQLite nyata, API CRUD, dan skrip Node yang berjalan — fondasi aplikasi web/mobile dengan backend data sungguhan.", "Data"),
        Capability("combo-automation-workflow", "Automation & Workflow Fusion", "⚙️", "Otomasi menyeluruh yang benar-benar berjalan: skrip & scheduler, workflow berulang, pipeline CI/CD, orkestrasi agen/task, dan verifikasi otomatis — dieksekusi nyata di cloud, bukan sekadar dijelaskan.", "Otomasi"),
        Capability("combo-translation-lang", "Translation & Multilingual Fusion", "🌍", "Terjemahan & lokalisasi berkualitas tinggi: pertahankan nada, konteks, dan istilah teknis; ubah konten lintas bahasa dengan akurasi budaya; hasilkan versi id/EN lengkap dari knowledge base.", "Konten & Media"),
        Capability("combo-rendering-everything", "Rendering All Formats", "🎨", "Render semua format jadi hasil nyata: markdown/dokumen jadi HTML/PDF, kode jadi visual/UI, data jadi laporan, presentasi & media AI (gambar/video) — semua dihasilkan dari logika & kode asli skill.", "Konten & Media"),
        Capability("combo-finops-cost", "FinOps & Cloud Cost Optimization", "💰", "Kontrol & tekan biaya cloud nyata: analisis data billing/cost (pakai CSV/SQL), buat budget & alerting, optimasi resource & model AI, dan beri rekomendasi penghematan yang terukur.", "Keuangan & Cloud"),
        Capability("combo-dataviz-reporting", "Data Visualization & Automated Reporting", "📈", "Ubah data jadi visual nyata: generate chart HTML dari data (bar/line/pie), rancang dashboard, dan susun laporan otomatis yang bisa diunduh — dieksekusi sungguhan, bukan mockup.", "Data"),
        Capability("combo-email-notifications", "Email & Unified Notifications", "📧", "Kirim & kelola komunikasi: compose email/notifikasi multi-kanal (email, slack, telegram) dengan template profesional, integrasi mailtrap/ops nyata, dan konsistensi nada brand.", "Notifikasi"),
        Capability("combo-backup-disaster-recovery", "Backup, Migrasi & Disaster Recovery", "🛟", "Lindungi data & sistem: strategi backup/restore & snapshot, migrasi database antar platform, dan rencana disaster recovery dengan urutan pemulihan yang teruji — bukan sekadar teori.", "Ops & Recovery"),
        Capability("combo-web-scraping-intel", "Web Scraping & Data Extraction", "🕷️", "Ekstraksi data web nyata: ambil halaman/API (tool fetch), parse HTML/JSON/CSV, bersihkan, lalu olah jadi dataset terstruktur yang siap dianalisis atau disimpan.", "Data"),
        Capability("combo-payment-fintech", "Payment, Billing & Fintech", "💳", "Integrasi & otomasi pembayaran: integrasi payment gateway (Stripe/PayPal), buat & tarik invoice, kelola transaksi/billing, dan otomasi penagihan — berjalan nyata dengan data contoh yang aman.", "Keuangan & Cloud"),
        Capability("combo-hr-recruitment", "HR & Recruitment Pipeline", "🧑‍💼", "Otomasi SDM & rekrutmen: susun deskripsi lowongan, saring kandidat (CV/resume), buat pertanyaan wawancara, email komunikasi kandidat, dan alur onboarding baru.", "Operasional"),
        Capability("combo-game-xr", "Game, 3D & XR Development", "🎮", "Rekayasa game, 3D & XR nyata: desain level/narasi, skrip gameplay lintas engine (Godot/Unity/Unreal), shader & ECS, multiplayer, audio, hingga pengalaman XR imersif — pola kode asli dari setiap skill dipadukan jadi satu alur produksi.", "Kreatif & Game"),
        Capability("combo-academic-research", "Academic & Scientific Research", "🎓", "Kajian akademik & ilmiah berstandar: metodologi riset lintas disiplin (sejarah, psikologi, antropologi, geografi), analisis statistik, eksperimen terdokumentasi, sitasi benar, dan laporan ilmiah yang dapat dipertanggungjawabkan.", "Riset & AI"),
        Capability("combo-healthcare-ai", "Healthcare & Medical AI", "🏥", "Inteligensi kesehatan yang aman & patuh: pola EMR/CDSS, kepatuhan PHI/HIPAA, evaluasi klinis & evidence-based, billing medis, dan arsitektur data kesehatan yang aman sejak desain.", "Riset & AI"),
        Capability("combo-project-delivery", "Project Management & Geospatial Delivery", "📐", "Kirim proyek tepat waktu & peta dunia nyata: perencanaan/sprint/roadmap dengan gate kualitas & manajemen stakeholder, lalu eksekusi geospasial (GIS/BIM, kartografi, pemetaan drone) yang teruji QA.", "Operasional"),
        Capability("combo-generalist-master", "Generalist & Operator Fusion", "🧰", "Kemampuan serba-bisa: menangkap semua skill lintas-kategori yang tidak masuk satu domain sempit — operasional umum, template, workflow campuran, dan troubleshooting fleksibel — agar tak ada pengetahuan yang terbuang.", "Operasional"),
        Capability("combo-secure-data-pipeline", "Secure Data Pipeline", "🗃️", "Pipeline data yang aman end-to-end: enkripsi, kontrol akses, audit trail, dan deteksi anomali — data mengalir cepat tanpa mengorbankan kepatuhan.", "Data"),
        Capability("combo-install-download", "Install, Download & Artifact Distribution", "📦", "Fusi total distribusi & instalasi: dari package manager (pip/npm/cargo/brew), containerization (Docker/Helm), infrastructure-as-code (Terraform/GKE), hingga CI/CD artifact pipeline — satu kemampuan terpadu untuk mengunduh, menginstal, membangun, dan mendistribusikan artefak apa pun di lingkungan apa pun.", "DevOps & Delivery"),
        Capability("combo-network-edge", "Network & Edge Engineering", "🌐", "Rekayasa jaringan end-to-end: dari konfigurasi BGP/VLAN/Firewall/WAF hingga service mesh (Istio/Linkerd), mTLS, DNS caching (Pi-hole), observability latency kritis, dan SSH automation — satu kemampuan terpadu untuk membangun, mengamankan, dan mengobservasi jaringan apa pun, edge maupun cloud.", "Jaringan"),
        Capability("combo-os-environment", "OS & Reproducible Environments", "🐧", "Lingkungan kerja yang portabel, aman, dan reproduksibel: manajemen env deklaratif (Flox/Nix), bash defensif produksi, shellcheck, BATS, secrets management, dan provisioning agen — satu kemampuan untuk menjalankan apa pun secara konsisten di lingkungan apa pun.", "Sistem & Performa"),
        Capability("combo-build-shipping", "Build App & Project Shipping Fusion", "🏗️", "Fusi total membangun & mengirim project: restrukturisasi semua logika kode build menjadi satu kemampuan — scaffold struktur project lengkap (Android/Gradle/Compose Multiplatform, web frontend/backend, React Native), kompilasi/bundling (Gradle, Vite, Next build), containerization (Docker/Cloud Build), manifest GKE/K8s, dan pipeline CI/CD shipping — dengan tool write nyata agar setiap file ditulis ke workspace dan hasilnya bisa diunduh. Terapkan pedoman before-you-build (piprah), arsitektur bersih, optimasi build (lean/bazel), dan emisi produksi yang siap dirilis.", "DevOps & Delivery"),
        Capability("combo-build-apk", "Android APK Build Pipeline", "🧱", "Fusi total membangun APK Android end-to-end: restrukturisasi semua logika kode build Android menjadi satu kemampuan — struktur project Gradle lengkap (settings.gradle, build.gradle root & app, gradle.properties, AndroidManifest.xml, res/values, MainActivity.kt), arsitektur bersih (clean architecture + MVVM), pola Kotlin/Compose/material design, sampai pipeline menghasilkan APK (assembleDebug/assembleRelease), signing (keystore/signingConfig), R8/ProGuard minify, dan distribusi AAB/APK — setiap file ditulis ke workspace memakai tool write agar source project bisa diunduh lalu di-build di Android Studio.", "DevOps & Delivery"),
    )

    fun byGroup(g: String): List<Capability> = all.filter { it.group == g }
}
